[package]
name = "firefly-audio"
version = "0.1.0"
edition = "2021"

[dependencies]
firefly-device = { path = "../firefly-device" }
micromath = "2.1.0"
wide = { version = "0.7.28", default-features = false }
